# Generated by Django 2.2.10 on 2020-09-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggunaanobat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datakunjungan',
            name='nama_dokter',
            field=models.CharField(choices=[('nur', 'dr. Nurul Pratiwi'), ('suz', 'dr. Suzi Leoni'), ('dwi', 'drg. Dwi Yosta C'), ('int', 'dr. Intan Larasati'), ('etc', 'Lainnya')], default='etc', max_length=3, verbose_name='Nama Dokter'),
            preserve_default=False,
        ),
    ]
