# Generated by Django 3.0.3 on 2020-02-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataObat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=20)),
                ('satuan', models.CharField(blank=True, help_text='Satuan pemakaian obat', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Data Obat',
            },
        ),
        migrations.CreateModel(
            name='DataPasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kartu', models.CharField(help_text='Masukkan no BPJS / KTP', max_length=20)),
                ('nama_pasien', models.CharField(help_text='Masukkan nama', max_length=30)),
                ('alamat', models.CharField(help_text='Masukkan alamat', max_length=50)),
                ('usia', models.DateField(help_text='Wajib diisi')),
                ('no_whatsapp', models.CharField(help_text='masukkan no whatsapp aktif pasien', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Data Pasien',
            },
        ),
    ]
