# Generated by Django 2.2.10 on 2020-09-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengingat', '0002_auto_20200312_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobat',
            name='ab',
            field=models.BooleanField(help_text='Check jika termasuk antibiotik', verbose_name='Antibiotik?'),
        ),
        migrations.AlterField(
            model_name='dataobat',
            name='nama_obat',
            field=models.CharField(help_text='Tulis nama obat dan dosisnya', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataobat',
            name='satuan',
            field=models.CharField(choices=[('TAB', 'Tablet'), ('SYR', 'Sirup'), ('CAP', 'Kapsul'), ('BKS', 'Bungkus'), ('SAL', 'Salep'), ('CRM', 'Krim'), ('PCS', 'Pcs'), ('BTL', 'Botol'), ('SET', 'Set'), ('KTK', 'Kotak')], help_text='Bentuk sediaan', max_length=3, verbose_name='Bentuk sediaan'),
        ),
    ]
